name: Schedule server increase
on:
  schedule:
    - cron: "04 05 * * *"
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
    
jobs:
  upscale:
    name: increase server capacity
    runs-on: ubuntu-latest
    environment: do
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/798920531034/locations/global/workloadIdentityPools/githubaction-pool/providers/my-provider'
        service_account: 'githubactions@apex-351704.iam.gserviceaccount.com'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
